# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 480, 791, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.bottonLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.bottonLayout.setContentsMargins(0, 0, 0, 0)
        self.bottonLayout.setObjectName("bottonLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 791, 421))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.centralLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.centralLayout.setObjectName("centralLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.horizontalLayoutWidget)
        self.treeView.setObjectName("treeView")
        self.centralLayout.addWidget(self.treeView)
        self.codeTab = QtWidgets.QTabWidget(parent=self.horizontalLayoutWidget)
        self.codeTab.setEnabled(True)
        self.codeTab.setObjectName("codeTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.codeTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.codeTab.addTab(self.tab_2, "")
        self.centralLayout.addWidget(self.codeTab)
        self.centralLayout.setStretch(0, 1)
        self.centralLayout.setStretch(1, 3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 791, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.topLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.topLayout.setContentsMargins(0, 0, 0, 0)
        self.topLayout.setObjectName("topLayout")
        self.startButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.startButton.setEnabled(True)
        self.startButton.setStyleSheet("background-color: green;\n"
"color: white;\n"
"")
        self.startButton.setObjectName("startButton")
        self.topLayout.addWidget(self.startButton)
        self.fakeLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.fakeLabel.setEnabled(False)
        self.fakeLabel.setText("")
        self.fakeLabel.setObjectName("fakeLabel")
        self.topLayout.addWidget(self.fakeLabel)
        self.topLayout.setStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 37))
        self.menubar.setObjectName("menubar")
        self.menuFRAg = QtWidgets.QMenu(parent=self.menubar)
        self.menuFRAg.setObjectName("menuFRAg")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFRAg.menuAction())

        self.retranslateUi(MainWindow)
        self.codeTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FRAg"))
        self.codeTab.setTabText(self.codeTab.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.codeTab.setTabText(self.codeTab.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.menuFRAg.setTitle(_translate("MainWindow", "FRAg"))
