# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 520, 791, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.bottonLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.bottonLayout.setContentsMargins(0, 0, 0, 0)
        self.bottonLayout.setObjectName("bottonLayout")
        self.configStatusLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.configStatusLabel.setWordWrap(True)
        self.configStatusLabel.setObjectName("configStatusLabel")
        self.bottonLayout.addWidget(self.configStatusLabel, 0, 1, 1, 1)
        self.staticConfigLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.staticConfigLabel.setObjectName("staticConfigLabel")
        self.bottonLayout.addWidget(self.staticConfigLabel, 0, 0, 1, 1)
        self.bottonLayout.setColumnStretch(0, 1)
        self.bottonLayout.setColumnStretch(1, 5)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 791, 461))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.centralLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.centralLayout.setObjectName("centralLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.horizontalLayoutWidget)
        self.treeView.setObjectName("treeView")
        self.centralLayout.addWidget(self.treeView)
        self.filesTab = QtWidgets.QTabWidget(parent=self.horizontalLayoutWidget)
        self.filesTab.setEnabled(True)
        self.filesTab.setTabsClosable(True)
        self.filesTab.setObjectName("filesTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.filesTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.filesTab.addTab(self.tab_2, "")
        self.centralLayout.addWidget(self.filesTab)
        self.centralLayout.setStretch(0, 1)
        self.centralLayout.setStretch(1, 3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 791, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.topLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.topLayout.setContentsMargins(0, 0, 0, 0)
        self.topLayout.setObjectName("topLayout")
        self.runButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.runButton.setEnabled(True)
        self.runButton.setStyleSheet("#runButton {\n"
"    background-color: green;\n"
"    color: white;\n"
"}\n"
"\n"
"#runButton:disabled {\n"
"    background-color: gray;\n"
"    color: lightgray;\n"
"}")
        self.runButton.setObjectName("runButton")
        self.topLayout.addWidget(self.runButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.saveButton.setObjectName("saveButton")
        self.topLayout.addWidget(self.saveButton)
        self.fakeLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.fakeLabel.setEnabled(False)
        self.fakeLabel.setText("")
        self.fakeLabel.setObjectName("fakeLabel")
        self.topLayout.addWidget(self.fakeLabel)
        self.topLayout.setStretch(2, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        self.menuFRAg = QtWidgets.QMenu(parent=self.menubar)
        self.menuFRAg.setObjectName("menuFRAg")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFRAg.menuAction())

        self.retranslateUi(MainWindow)
        self.filesTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FRAg"))
        self.configStatusLabel.setText(_translate("MainWindow", "Configuration path"))
        self.staticConfigLabel.setText(_translate("MainWindow", "Active configuration:"))
        self.filesTab.setTabText(self.filesTab.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.filesTab.setTabText(self.filesTab.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.menuFRAg.setTitle(_translate("MainWindow", "FRAg"))
