


coords(a,[1,1]).
coords(b,[2,1]).
coords(c,[3,1]).
coords(d,[4,1]).
coords(e,[5,1]).
coords(f,[6,1]).
coords(g,[1,2]).
coords(h,[2,2]).
coords(i,[3,2]).
coords(j,[4,2]).
coords(k,[5,2]).
coords(l,[6,2]).
coords(m,[1,3]).
coords(n,[2,3]).
coords(o,[3,3]).
coords(p,[4,3]).
coords(q,[5,3]).
coords(r,[6,3]).
coords(s,[1,4]).
coords(t,[2,4]).
coords(u,[3,4]).
coords(v,[4,4]).
coords(w,[5,4]).
coords(x,[6,4]).
coords(y,[1,5]).
coords(z,[2,5]).
coords(aa,[3,5]).
coords(ab,[4,5]).
coords(ac,[5,5]).
coords(ad,[6,5]).
coords(ae,[1,6]).
coords(af,[2,6]).
coords(ag,[3,6]).
coords(ah,[4,6]).
coords(ai,[5,6]).
coords(aj,[6,6]).


item([2,2], gold).
item([3,3], gold).
item([4,4], gold).                                                   
item([5,5], gold).
item([6,6], gold).

path([A,B],[C,B]):-C is A+1.
path([A,B],[A,C]):-C is B+1.

size_x(6).
size_y(6).


direction(a,b,right).
direction(a,c,right).
direction(a,d,right).
direction(a,e,right).
direction(a,f,right).
direction(a,g,down).
direction(a,h,down).
direction(a,i,down).
direction(a,j,down).
direction(a,k,down).
direction(a,l,down).
direction(a,m,down).
direction(a,n,down).
direction(a,o,down).
direction(a,p,down).
direction(a,q,down).
direction(a,r,down).
direction(a,s,down).
direction(a,t,down).
direction(a,u,down).
direction(a,v,down).
direction(a,w,down).
direction(a,x,down).
direction(a,y,down).
direction(a,z,down).
direction(a,aa,down).
direction(a,ab,down).
direction(a,ac,down).
direction(a,ad,down).
direction(a,ae,down).
direction(a,af,down).
direction(a,ag,down).
direction(a,ah,down).
direction(a,ai,down).
direction(a,aj,down).
direction(b,c,right).
direction(b,d,right).
direction(b,e,right).
direction(b,f,right).
direction(b,h,down).
direction(b,i,down).
direction(b,j,down).
direction(b,k,down).
direction(b,l,down).
direction(b,n,down).
direction(b,o,down).
direction(b,p,down).
direction(b,q,down).
direction(b,r,down).
direction(b,t,down).
direction(b,u,down).
direction(b,v,down).
direction(b,w,down).
direction(b,x,down).
direction(b,z,down).
direction(b,aa,down).
direction(b,ab,down).
direction(b,ac,down).
direction(b,ad,down).
direction(b,af,down).
direction(b,ag,down).
direction(b,ah,down).
direction(b,ai,down).
direction(b,aj,down).
direction(c,d,right).
direction(c,e,right).
direction(c,f,right).
direction(c,i,down).
direction(c,j,down).
direction(c,k,down).
direction(c,l,down).
direction(c,o,down).
direction(c,p,down).
direction(c,q,down).
direction(c,r,down).
direction(c,u,down).
direction(c,v,down).
direction(c,w,down).
direction(c,x,down).
direction(c,aa,down).
direction(c,ab,down).
direction(c,ac,down).
direction(c,ad,down).
direction(c,ag,down).
direction(c,ah,down).
direction(c,ai,down).
direction(c,aj,down).
direction(d,e,right).
direction(d,f,right).
direction(d,j,down).
direction(d,k,down).
direction(d,l,down).
direction(d,p,down).
direction(d,q,down).
direction(d,r,down).
direction(d,v,down).
direction(d,w,down).
direction(d,x,down).
direction(d,ab,down).
direction(d,ac,down).
direction(d,ad,down).
direction(d,ah,down).
direction(d,ai,down).
direction(d,aj,down).
direction(e,f,right).
direction(e,k,down).
direction(e,l,down).
direction(e,q,down).
direction(e,r,down).
direction(e,w,down).
direction(e,x,down).
direction(e,ac,down).
direction(e,ad,down).
direction(e,ai,down).
direction(e,aj,down).
direction(f,l,down).
direction(f,r,down).
direction(f,x,down).
direction(f,ad,down).
direction(f,aj,down).
direction(g,h,right).
direction(g,i,right).
direction(g,j,right).
direction(g,k,right).
direction(g,l,right).
direction(g,m,down).
direction(g,n,down).
direction(g,o,down).
direction(g,p,down).
direction(g,q,down).
direction(g,r,down).
direction(g,s,down).
direction(g,t,down).
direction(g,u,down).
direction(g,v,down).
direction(g,w,down).
direction(g,x,down).
direction(g,y,down).
direction(g,z,down).
direction(g,aa,down).
direction(g,ab,down).
direction(g,ac,down).
direction(g,ad,down).
direction(g,ae,down).
direction(g,af,down).
direction(g,ag,down).
direction(g,ah,down).
direction(g,ai,down).
direction(g,aj,down).
direction(h,i,right).
direction(h,j,right).
direction(h,k,right).
direction(h,l,right).
direction(h,n,down).
direction(h,o,down).
direction(h,p,down).
direction(h,q,down).
direction(h,r,down).
direction(h,t,down).
direction(h,u,down).
direction(h,v,down).
direction(h,w,down).
direction(h,x,down).
direction(h,z,down).
direction(h,aa,down).
direction(h,ab,down).
direction(h,ac,down).
direction(h,ad,down).
direction(h,af,down).
direction(h,ag,down).
direction(h,ah,down).
direction(h,ai,down).
direction(h,aj,down).
direction(i,j,right).
direction(i,k,right).
direction(i,l,right).
direction(i,o,down).
direction(i,p,down).
direction(i,q,down).
direction(i,r,down).
direction(i,u,down).
direction(i,v,down).
direction(i,w,down).
direction(i,x,down).
direction(i,aa,down).
direction(i,ab,down).
direction(i,ac,down).
direction(i,ad,down).
direction(i,ag,down).
direction(i,ah,down).
direction(i,ai,down).
direction(i,aj,down).
direction(j,k,right).
direction(j,l,right).
direction(j,p,down).
direction(j,q,down).
direction(j,r,down).
direction(j,v,down).
direction(j,w,down).
direction(j,x,down).
direction(j,ab,down).
direction(j,ac,down).
direction(j,ad,down).
direction(j,ah,down).
direction(j,ai,down).
direction(j,aj,down).
direction(k,l,right).
direction(k,q,down).
direction(k,r,down).
direction(k,w,down).
direction(k,x,down).
direction(k,ac,down).
direction(k,ad,down).
direction(k,ai,down).
direction(k,aj,down).
direction(l,r,down).
direction(l,x,down).
direction(l,ad,down).
direction(l,aj,down).
direction(m,n,right).
direction(m,o,right).
direction(m,p,right).
direction(m,q,right).
direction(m,r,right).
direction(m,s,down).
direction(m,t,down).
direction(m,u,down).
direction(m,v,down).
direction(m,w,down).
direction(m,x,down).
direction(m,y,down).
direction(m,z,down).
direction(m,aa,down).
direction(m,ab,down).
direction(m,ac,down).
direction(m,ad,down).
direction(m,ae,down).
direction(m,af,down).
direction(m,ag,down).
direction(m,ah,down).
direction(m,ai,down).
direction(m,aj,down).
direction(n,o,right).
direction(n,p,right).
direction(n,q,right).
direction(n,r,right).
direction(n,t,down).
direction(n,u,down).
direction(n,v,down).
direction(n,w,down).
direction(n,x,down).
direction(n,z,down).
direction(n,aa,down).
direction(n,ab,down).
direction(n,ac,down).
direction(n,ad,down).
direction(n,af,down).
direction(n,ag,down).
direction(n,ah,down).
direction(n,ai,down).
direction(n,aj,down).
direction(o,p,right).
direction(o,q,right).
direction(o,r,right).
direction(o,u,down).
direction(o,v,down).
direction(o,w,down).
direction(o,x,down).
direction(o,aa,down).
direction(o,ab,down).
direction(o,ac,down).
direction(o,ad,down).
direction(o,ag,down).
direction(o,ah,down).
direction(o,ai,down).
direction(o,aj,down).
direction(p,q,right).
direction(p,r,right).
direction(p,v,down).
direction(p,w,down).
direction(p,x,down).
direction(p,ab,down).
direction(p,ac,down).
direction(p,ad,down).
direction(p,ah,down).
direction(p,ai,down).
direction(p,aj,down).
direction(q,r,right).
direction(q,w,down).
direction(q,x,down).
direction(q,ac,down).
direction(q,ad,down).
direction(q,ai,down).
direction(q,aj,down).
direction(r,x,down).
direction(r,ad,down).
direction(r,aj,down).
direction(s,t,right).
direction(s,u,right).
direction(s,v,right).
direction(s,w,right).
direction(s,x,right).
direction(s,y,down).
direction(s,z,down).
direction(s,aa,down).
direction(s,ab,down).
direction(s,ac,down).
direction(s,ad,down).
direction(s,ae,down).
direction(s,af,down).
direction(s,ag,down).
direction(s,ah,down).
direction(s,ai,down).
direction(s,aj,down).
direction(t,u,right).
direction(t,v,right).
direction(t,w,right).
direction(t,x,right).
direction(t,z,down).
direction(t,aa,down).
direction(t,ab,down).
direction(t,ac,down).
direction(t,ad,down).
direction(t,af,down).
direction(t,ag,down).
direction(t,ah,down).
direction(t,ai,down).
direction(t,aj,down).
direction(u,v,right).
direction(u,w,right).
direction(u,x,right).
direction(u,aa,down).
direction(u,ab,down).
direction(u,ac,down).
direction(u,ad,down).
direction(u,ag,down).
direction(u,ah,down).
direction(u,ai,down).
direction(u,aj,down).
direction(v,w,right).
direction(v,x,right).
direction(v,ab,down).
direction(v,ac,down).
direction(v,ad,down).
direction(v,ah,down).
direction(v,ai,down).
direction(v,aj,down).
direction(w,x,right).
direction(w,ac,down).
direction(w,ad,down).
direction(w,ai,down).
direction(w,aj,down).
direction(x,ad,down).
direction(x,aj,down).
direction(y,z,right).
direction(y,aa,right).
direction(y,ab,right).
direction(y,ac,right).
direction(y,ad,right).
direction(y,ae,down).
direction(y,af,down).
direction(y,ag,down).
direction(y,ah,down).
direction(y,ai,down).
direction(y,aj,down).
direction(z,aa,right).
direction(z,ab,right).
direction(z,ac,right).
direction(z,ad,right).
direction(z,af,down).
direction(z,ag,down).
direction(z,ah,down).
direction(z,ai,down).
direction(z,aj,down).
direction(aa,ab,right).
direction(aa,ac,right).
direction(aa,ad,right).
direction(aa,ag,down).
direction(aa,ah,down).
direction(aa,ai,down).
direction(aa,aj,down).
direction(ab,ac,right).
direction(ab,ad,right).
direction(ab,ah,down).
direction(ab,ai,down).
direction(ab,aj,down).
direction(ac,ad,right).
direction(ac,ai,down).
direction(ac,aj,down).
direction(ad,aj,down).
direction(ae,af,right).
direction(ae,ag,right).
direction(ae,ah,right).
direction(ae,ai,right).
direction(ae,aj,right).
direction(af,ag,right).
direction(af,ah,right).
direction(af,ai,right).
direction(af,aj,right).
direction(ag,ah,right).
direction(ag,ai,right).
direction(ag,aj,right).
direction(ah,ai,right).
direction(ah,aj,right).
direction(ai,aj,right).
